### ISSUE TITLE
nb-user error

### ISSUE THREAD

**Issue by aligredo** [omardoma/angular-seed-project#1]
Whenever I start the seed web app the spinner keeps spinning around and the page doesn't load and I found this error in the console 

Error: Template parse errors:
Can't bind to 'menu' since it isn't a known property of 'nb-user'.
1. If 'nb-user' is an Angular component and it has 'menu' input, then verify that it is part of this module.
2. If 'nb-user' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<nb-actions size="medium" class="header-container right">
  <nb-action>
    <nb-user [ERROR ->][menu]="userMenu" [name]="user?.username" (menuClick)="onMenuClick($event)"></nb-user>
  </nb-action>"): ng:///ThemeModule/HeaderComponent.html@14:13
vendor.bundle.js%20line%202816%20%3E%20eval:706:34

I checked the documentation and i didn't fined "menu" in nb-user component However, it works for other people.

**Comment by omardoma** [comment]
Fixed, please pull the changes on the master branch to update your seed project, Closing the issue.
